name: skillorbit
description: "A modern AI based learning app built by 'Skill Orbit' using Flutter and Firebase."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter

  # State management
  get: ^4.7.2

  # Google Fonts
  google_fonts: ^5.0.0

  cupertino_icons: ^1.0.8

  # Add Firebase Core (Required for all Firebase services)
  firebase_core: ^3.8.0

  # Add Firestore (Cloud Firestore Database)
  cloud_firestore: ^5.5.0

  # SVG Image Support
  flutter_svg: ^2.0.0+1

  # (Optional but recommended if you plan to use login system)
  # firebase_auth: ^5.3.3

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

assets:
  - lib/core/assets/images