// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDSblZWo4KUenNjTIykjt2rwI6RE0I9q4k',
    appId: '1:624647627911:web:b92cb7123699ec2b880422',
    messagingSenderId: '624647627911',
    projectId: 'skill-orbit-754',
    authDomain: 'skill-orbit-754.firebaseapp.com',
    storageBucket: 'skill-orbit-754.firebasestorage.app',
    measurementId: 'G-DL18VNLEQD',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDh3-gnMl0jTAba2ORgEIo5mHalUtPdc-4',
    appId: '1:624647627911:android:c7a5c15a331f5b00880422',
    messagingSenderId: '624647627911',
    projectId: 'skill-orbit-754',
    storageBucket: 'skill-orbit-754.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCGWZjrSWvARxd4XJqnP17OW_zLcIkXepo',
    appId: '1:624647627911:ios:04b39334a3c591ca880422',
    messagingSenderId: '624647627911',
    projectId: 'skill-orbit-754',
    storageBucket: 'skill-orbit-754.firebasestorage.app',
    iosBundleId: 'com.skillorbit.skillorbit',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCGWZjrSWvARxd4XJqnP17OW_zLcIkXepo',
    appId: '1:624647627911:ios:04b39334a3c591ca880422',
    messagingSenderId: '624647627911',
    projectId: 'skill-orbit-754',
    storageBucket: 'skill-orbit-754.firebasestorage.app',
    iosBundleId: 'com.skillorbit.skillorbit',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDSblZWo4KUenNjTIykjt2rwI6RE0I9q4k',
    appId: '1:624647627911:web:bda3587bb0950746880422',
    messagingSenderId: '624647627911',
    projectId: 'skill-orbit-754',
    authDomain: 'skill-orbit-754.firebaseapp.com',
    storageBucket: 'skill-orbit-754.firebasestorage.app',
    measurementId: 'G-GV6CRK2RS3',
  );

}